spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: garvinzhang@foxmail.com
    password: cctdqyvmoecvbhbg
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            