spring:
  application:
    name: demo

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
      jedis:
        pool:
          max-wait: 10000
          max-active: 100
          max-idle: 10
      database: 0
      timeout: 5000

#      <dependency>
#      <groupId>org.springframework.boot</groupId>
#      <artifactId>spring-boot-starter-data-redis</artifactId>
#      </dependency>