server:
  port: 9999

spring:
  application:
    name: object-storage-center
  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        server-addr: ${NACOS_HOST:localhost:8848}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        namespace: ${NAME_SPACE:3408f699-afe4-43b5-99d2-949141068cba}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        group: ${spring.cloud.nacos.discovery.group}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:nacos:base-config.yml
      - optional:nacos:object-storage-center.yml
